### ISSUE TITLE
rho=0.99 in simulated dataset is huge

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchmark_slope#5]
It leads to very specific behaviors. Something like 0.8 would be more reasonable. @AmelieVernay could you send a PR to address this?

**Comment by jolars** [comment]
Maybe, I guess it depends on the number of features. I've run simulations on this setup previously (even going to 0.999), and I think it's a reasonable scenario. `rho = 0.8` is going to make very little difference for a solver, and especially screening rules, when the numer of features is say a million. It might make more sense to tie rho to the specific n_features/n_samples setting like we do for X_density and n_signals.
